name = "talk"
main = "chat.js"
compatibility_date = "2026-08-25"
workers_dev = true
preview_urls = false
logpush = false

[observability]
enabled = false

[observability.logs]
invocation_logs = false
